### ISSUE TITLE
create new GCP project

### ISSUE THREAD

**Issue by Burwin** [BambooSoftwareLLC/sprout#2]
# Summary
The script creates a new GCP project.

# Tasks
- [ ] Fail if user is not logged in to GCP
- [ ] Provide instructions to user to login to GCP
- [ ] Create GCP project and wait until it's finished
- [ ] Store GCP project info in memory
- [ ] Output GCP project info on completion
