### ISSUE TITLE
create VueJS app

### ISSUE THREAD

**Issue by Burwin** [BambooSoftwareLLC/sprout#5]
# Summary
Need to create a full VueJS template app

# Tasks
- [x] #6
- [x] #8
- [ ] Add Firebase Auth to app
- [ ] Add Landing Page
- [ ] Add Sign-in screen
- [ ] Add sign-up screen
- [ ] Add skeleton authenticated dashboard
